CREATE DATABASE IF NOT EXISTS m2oath_web
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS m2oath_trust
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

CREATE DATABASE IF NOT EXISTS m2oath_weather
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;
